package Budget_Planner.Model;

public interface DataConstants {

    String DB_NAME = "transactions.db";
    String PATH = System.getProperty("user.dir");
    String CONNECTION_STRING = "jdbc:sqlite:" + PATH + "\\" + DB_NAME;

    String TABLE_TRANSACTIONS = "transactions";
    String TABLE_ACCOUNTS = "accounts";

    String COLUMN_TRANSACTIONS_ID = "id";
    String COLUMN_TRANSACTIONS_TITLE = "title";
    String COLUMN_TRANSACTIONS_AMOUNT = "amount";
    String COLUMN_TRANSACTIONS_DATE = "date";
    String COLUMN_TRANSACTIONS_TYPE = "type";
    String COLUMN_TRANSACTIONS_ACCOUNT_ID = "account";

    String COLUMN_ACCOUNT_LOGIN = "login";
    String COLUMN_ACCOUNT_PASSWORD = "password";

    String DEPOSIT = "Deposit";
    String PAYMENT = "Payment";

    String CREATE_ACCOUNT_TABLE = " CREATE TABLE IF NOT EXISTS " + TABLE_ACCOUNTS + " ( "  + COLUMN_ACCOUNT_LOGIN + " TEXT, "
            + COLUMN_ACCOUNT_PASSWORD + " TEXT)";

    String INSERT_ACCOUNT = "INSERT INTO " + TABLE_ACCOUNTS + "( " + COLUMN_ACCOUNT_LOGIN + " , " + COLUMN_ACCOUNT_PASSWORD +
            ") VALUES(?,?)" ;

    String ACCOUNT_LOOKUP = "SELECT * FROM " + TABLE_ACCOUNTS + " WHERE " + COLUMN_ACCOUNT_LOGIN + " = ?";
    
    String CREATE_TRANSACTION_TABLE = "CREATE TABLE IF NOT EXISTS " + TABLE_TRANSACTIONS + " ( "+ COLUMN_TRANSACTIONS_ID + " INT, " + COLUMN_TRANSACTIONS_TITLE + " TEXT , " +
            COLUMN_TRANSACTIONS_AMOUNT + " DOUBLE, " + COLUMN_TRANSACTIONS_DATE + " DATE, " + COLUMN_TRANSACTIONS_TYPE + " TEXT, " + COLUMN_TRANSACTIONS_ACCOUNT_ID + ", TEXT)";

    String INSERT_TRANSACTION = "INSERT INTO " + TABLE_TRANSACTIONS + "( "+ COLUMN_TRANSACTIONS_ID + ", " +
            COLUMN_TRANSACTIONS_TITLE + ", " + COLUMN_TRANSACTIONS_AMOUNT + ", " + COLUMN_TRANSACTIONS_DATE + ", " +
            COLUMN_TRANSACTIONS_TYPE + ", " + COLUMN_TRANSACTIONS_ACCOUNT_ID + ") VALUES(?,?,?,?,?,?)";

    String SHOW_TRANSACTIONS = "SELECT * FROM " + TABLE_TRANSACTIONS + " WHERE " + COLUMN_TRANSACTIONS_DATE + " BETWEEN ? AND ? " + " AND " + COLUMN_TRANSACTIONS_ACCOUNT_ID + " = ? " +
            " ORDER BY " + COLUMN_TRANSACTIONS_DATE + " DESC";

    String SHOW_DEPOSITS = "SELECT * FROM " + TABLE_TRANSACTIONS + " WHERE "+ COLUMN_TRANSACTIONS_TYPE + " = '" + DEPOSIT + "' AND " + COLUMN_TRANSACTIONS_DATE + " BETWEEN ? AND ? " +
            " AND " + COLUMN_TRANSACTIONS_ACCOUNT_ID + " = ? " +
            " ORDER BY " + COLUMN_TRANSACTIONS_DATE + " DESC";

    String SHOW_PAYMENTS = "SELECT * FROM " + TABLE_TRANSACTIONS + " WHERE "+ COLUMN_TRANSACTIONS_TYPE + " = '" + PAYMENT + "' AND " + COLUMN_TRANSACTIONS_DATE + " BETWEEN ? AND ? " +
            " AND " + COLUMN_TRANSACTIONS_ACCOUNT_ID + " = ? " +
            " ORDER BY " + COLUMN_TRANSACTIONS_DATE + " DESC";

    String SHOW_TITLES_DEPOSITS = "SELECT DISTINCT " + COLUMN_TRANSACTIONS_TITLE + " FROM " + TABLE_TRANSACTIONS + " WHERE " + COLUMN_TRANSACTIONS_TYPE + " LIKE  '%" + DEPOSIT + "%'";
    String SHOW_TITLES_PAYMENTS = "SELECT DISTINCT " + COLUMN_TRANSACTIONS_TITLE + " FROM " + TABLE_TRANSACTIONS + " WHERE " + COLUMN_TRANSACTIONS_TYPE + " LIKE  '%" + PAYMENT + "%'";


    String DEPOSIT_SUMMARY = "SELECT SUM(" + COLUMN_TRANSACTIONS_AMOUNT + ") FROM " + TABLE_TRANSACTIONS + " WHERE " + COLUMN_TRANSACTIONS_TYPE + " LIKE '%" + DEPOSIT + "%' AND " + COLUMN_TRANSACTIONS_DATE + " BETWEEN ? AND ? " +
            " AND " + COLUMN_TRANSACTIONS_ACCOUNT_ID + " = ? ";
    String PAYMENT_SUMMARY = "SELECT SUM(" + COLUMN_TRANSACTIONS_AMOUNT + ") FROM " + TABLE_TRANSACTIONS + " WHERE " + COLUMN_TRANSACTIONS_TYPE + " LIKE '%" + PAYMENT + "%' AND " + COLUMN_TRANSACTIONS_DATE + " BETWEEN ? AND ? " +
            " AND " + COLUMN_TRANSACTIONS_ACCOUNT_ID + " = ? ";

    String DELETE_TRANSACTION = "DELETE FROM " + TABLE_TRANSACTIONS + " WHERE " + COLUMN_TRANSACTIONS_ID + " = ? ";

}